"""added secritpion of the consumer column in ccm table

Revision ID: 82162cb3eab5
Revises: 286023c0bb57
Create Date: 2025-09-14 19:31:29.066534

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "82162cb3eab5"
down_revision: Union[str, Sequence[str], None] = "286023c0bb57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("client_requirement_products")
    op.drop_table("client_requirement")
    op.add_column(
        "clientconsumer",
        sa.Column(
            "clinet_consumer_requirement",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clientconsumer", "clinet_consumer_requirement")
    op.create_table(
        "client_requirement_products",
        sa.Column("crp_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("creq_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("prd_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["creq_id"],
            ["client_requirement.creq_id"],
            name=op.f("client_requirement_products_creq_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prd_id"],
            ["product.prd_id"],
            name=op.f("client_requirement_products_prd_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "crp_id", name=op.f("client_requirement_products_pkey")
        ),
    )
    op.create_table(
        "client_requirement",
        sa.Column("creq_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("client_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("creq_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
            name=op.f("client_requirement_client_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("creq_id", name=op.f("client_requirement_pkey")),
    )
    # ### end Alembic commands ###
