"""Added req_kilo_watt for requirement table

Revision ID: 286023c0bb57
Revises: 833cd2554da4
Create Date: 2025-09-14 14:29:22.041325

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "286023c0bb57"
down_revision: Union[str, Sequence[str], None] = "833cd2554da4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requirement",
        sa.Column("req_kilo_watt", sa.Integer(), nullable=False, server_default="2"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requirement", "req_kilo_watt")
    # ### end Alembic commands ###
