"""added clinet consumer table

Revision ID: 42e89693579e
Revises: 2d5f3ce1bc30
Create Date: 2025-09-12 20:29:34.774317

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42e89693579e"
down_revision: Union[str, Sequence[str], None] = "2d5f3ce1bc30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clientconsumer",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column(
            "clinet_consumer_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "clinet_consumer_phone_number",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "clinet_consumer_nick_name",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "clinet_consumer_meter_type",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("clinet_consumer_demand_load", sa.Integer(), nullable=False),
        sa.Column("clinet_consumed_demand_phase", sa.Integer(), nullable=False),
        sa.Column("client_consumer_max_consumed_units", sa.Integer(), nullable=False),
        sa.Column("client_consumer_avg_consumed_unit", sa.Integer(), nullable=False),
        sa.Column("client_consumer_peak_demand", sa.Integer(), nullable=False),
        sa.Column("client_consumer_avg_demand", sa.Integer(), nullable=False),
        sa.Column("ccm_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.client_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ccm_id"),
    )
    op.drop_column("clients", "client_shipping_to_1")
    op.drop_column("clients", "client_ba_holder_name")
    op.drop_column("clients", "client_ba_ifsc_no")
    op.drop_column("clients", "client_billing_to_1")
    op.drop_column("clients", "client_ba_branch")
    op.drop_column("clients", "client_shipping_to_3")
    op.drop_column("clients", "client_billing_to_3")
    op.drop_column("clients", "client_ba_acc_no")
    op.drop_column("clients", "client_shipping_to_2")
    op.drop_column("clients", "client_billing_to_2")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column(
            "client_billing_to_2", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_shipping_to_2", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_ba_acc_no",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_billing_to_3", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_shipping_to_3", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_ba_branch", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_billing_to_1", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_ba_ifsc_no",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_ba_holder_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_shipping_to_1", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_table("clientconsumer")
    # ### end Alembic commands ###
