"""added Quotation Table

Revision ID: 7f3cac795e45
Revises: 7eb932f2fe94
Create Date: 2025-09-09 21:26:36.279486

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f3cac795e45"
down_revision: Union[str, Sequence[str], None] = "7eb932f2fe94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quotation",
        sa.Column("quot_id", sa.Uuid(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("quot_expire_date", sa.Integer(), nullable=False),
        sa.Column(
            "quot_billing_to_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "quot_billing_to_2", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "quot_billing_to_3", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "quot_billing_from_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "quot_billing_from_2", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "quot_billing_from_3", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "quot_ba_holder_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("quot_ba_acc_no", sa.Integer(), nullable=False),
        sa.Column("quot_ba_ifsc_no", sa.Integer(), nullable=False),
        sa.Column("quot_ba_branch", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quot_warranty_panel", sa.Integer(), nullable=False),
        sa.Column("quot_warranty_Inverter", sa.Integer(), nullable=False),
        sa.Column("quot_warranty_battery", sa.Integer(), nullable=False),
        sa.Column("req_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["req_id"], ["requirement.req_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("quot_id"),
    )
    op.add_column(
        "product",
        sa.Column(
            "description",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="Please add the Description",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "description")
    op.drop_table("quotation")
    # ### end Alembic commands ###
