"""unique contraint for the data

Revision ID: e958e2a36ce6
Revises: 5ad4ef62d758
Create Date: 2025-08-24 13:49:47.502922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e958e2a36ce6'
down_revision: Union[str, Sequence[str], None] = '5ad4ef62d758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_req_prod', 'requirementproducts', ['req_id', 'prod_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_req_prod', 'requirementproducts', type_='unique')
    # ### end Alembic commands ###
