"""Added is_deleted_filed in the clinet table

Revision ID: 8a84cff31d8e
Revises: 4747694fdc57
Create Date: 2025-09-13 22:03:43.228994

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a84cff31d8e"
down_revision: Union[str, Sequence[str], None] = "4747694fdc57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "is_deleted")
    # ### end Alembic commands ###
