"""modified clinet consumer deault value

Revision ID: 8d3b54c1ed4d
Revises: 42e89693579e
Create Date: 2025-09-12 21:11:18.861858

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d3b54c1ed4d"
down_revision: Union[str, Sequence[str], None] = "42e89693579e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clientconsumer",
        "clinet_consumer_meter_type",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "clientconsumer",
        "client_consumer_max_consumed_units",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "clientconsumer",
        "client_consumer_avg_consumed_unit",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "clientconsumer",
        "client_consumer_peak_demand",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "clientconsumer",
        "client_consumer_avg_demand",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clientconsumer",
        "client_consumer_avg_demand",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "clientconsumer",
        "client_consumer_peak_demand",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "clientconsumer",
        "client_consumer_avg_consumed_unit",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "clientconsumer",
        "client_consumer_max_consumed_units",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "clientconsumer",
        "clinet_consumer_meter_type",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
