"""added table consumer requirement and consumer requirement product

Revision ID: 53c79f2348c8
Revises: 82162cb3eab5
Create Date: 2025-09-14 20:16:33.226279

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c79f2348c8'
down_revision: Union[str, Sequence[str], None] = '82162cb3eab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_requirement',
    sa.Column('con_req_id', sa.Uuid(), nullable=False),
    sa.Column('ccm_id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('creq_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consumer_requirement_descriptin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposed_recommandation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['ccm_id'], ['clientconsumer.ccm_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('con_req_id')
    )
    op.create_index(op.f('ix_client_requirement_ccm_id'), 'client_requirement', ['ccm_id'], unique=False)
    op.create_table('consumer_requirement_products',
    sa.Column('conrp_id', sa.Uuid(), nullable=False),
    sa.Column('con_req_id', sa.Uuid(), nullable=False),
    sa.Column('prd_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['con_req_id'], ['client_requirement.con_req_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prd_id'], ['product.prd_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conrp_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumer_requirement_products')
    op.drop_index(op.f('ix_client_requirement_ccm_id'), table_name='client_requirement')
    op.drop_table('client_requirement')
    # ### end Alembic commands ###
