"""added client, requirement for clinets table

Revision ID: 7e3f53b84ffe
Revises: 442ea77b9a41
Create Date: 2025-09-09 23:52:43.344376

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e3f53b84ffe"
down_revision: Union[str, Sequence[str], None] = "442ea77b9a41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_requirement",
        sa.Column("creq_id", sa.Uuid(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.client_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("creq_id"),
    )
    op.create_table(
        "client_requirement_products",
        sa.Column("crp_id", sa.Uuid(), nullable=False),
        sa.Column("creq_id", sa.Uuid(), nullable=False),
        sa.Column("prd_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creq_id"], ["client_requirement.creq_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["prd_id"], ["product.prd_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("crp_id"),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_shipping_to_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_shipping_to_2", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_shipping_to_3", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.drop_column("clients", "client_billing_from_3")
    op.drop_column("clients", "client_billing_from_2")
    op.drop_column("clients", "client_billing_from_1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column(
            "client_billing_from_1", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_billing_from_2", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "clients",
        sa.Column(
            "client_billing_from_3", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("clients", "client_shipping_to_3")
    op.drop_column("clients", "client_shipping_to_2")
    op.drop_column("clients", "client_shipping_to_1")
    op.drop_table("client_requirement_products")
    op.drop_table("client_requirement")
    # ### end Alembic commands ###
