"""added casecade delete

Revision ID: 7eb932f2fe94
Revises: e958e2a36ce6
Create Date: 2025-09-09 21:06:33.077969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7eb932f2fe94"
down_revision: Union[str, Sequence[str], None] = "e958e2a36ce6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("requirementproducts_req_id_fkey"),
        "requirementproducts",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "requirementproducts",
        "requirement",
        ["req_id"],
        ["req_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "requirementproducts", type_="foreignkey")
    op.create_foreign_key(
        op.f("requirementproducts_req_id_fkey"),
        "requirementproducts",
        "requirement",
        ["req_id"],
        ["req_id"],
    )
    # ### end Alembic commands ###
