"""Added battery backup for the consumer_appliances table

Revision ID: 07c3521d9100
Revises: 3bb71a6981d6
Create Date: 2025-09-14 00:17:33.302773

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07c3521d9100"
down_revision: Union[str, Sequence[str], None] = "3bb71a6981d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "consumerappliancesusage",
        sa.Column(
            "need_battery_backup", sa.Boolean(), nullable=False, server_default="true"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("consumerappliancesusage", "need_battery_backup")
    # ### end Alembic commands ###
