"""Added index for the foreign key for the view usage

Revision ID: 833cd2554da4
Revises: 07c3521d9100
Create Date: 2025-09-14 13:32:59.274188

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "833cd2554da4"
down_revision: Union[str, Sequence[str], None] = "07c3521d9100"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_clientconsumer_client_id"),
        "clientconsumer",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumerappliancesusage_ccm_id"),
        "consumerappliancesusage",
        ["ccm_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_consumerappliancesusage_ccm_id"), table_name="consumerappliancesusage"
    )
    op.drop_index(op.f("ix_clientconsumer_client_id"), table_name="clientconsumer")
    # ### end Alembic commands ###
