"""Added applicance

Revision ID: dc3c2b3d6c8b
Revises: 8d3b54c1ed4d
Create Date: 2025-09-13 00:35:15.843290

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc3c2b3d6c8b"
down_revision: Union[str, Sequence[str], None] = "8d3b54c1ed4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appliances",
        sa.Column("appliance_id", sa.Uuid(), nullable=False),
        sa.Column("appliance_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("appliance_volt", sa.Float(), nullable=False),
        sa.Column(
            "appliance_load_type",
            sa.Enum("LIGHT", "HEAVY", "INDUCTION", name="applianceloadtype"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("appliance_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("appliances")
    # ### end Alembic commands ###
