"""added column creq_name for the naming of the new client requirement

Revision ID: 2d5f3ce1bc30
Revises: 1441a9c453f1
Create Date: 2025-09-10 01:08:07.255639

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d5f3ce1bc30"
down_revision: Union[str, Sequence[str], None] = "1441a9c453f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_requirement",
        sa.Column("creq_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_requirement", "creq_name")
    # ### end Alembic commands ###
