"""empty message

Revision ID: 5ad4ef62d758
Revises:
Create Date: 2025-08-24 00:47:58.166810

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ad4ef62d758"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("ctg_id", sa.Uuid(), nullable=False),
        sa.Column("ctg_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("ctg_id"),
    )
    op.create_table(
        "requirement",
        sa.Column("req_id", sa.Uuid(), nullable=False),
        sa.Column("req_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("req_id"),
    )
    op.create_table(
        "product",
        sa.Column("prd_id", sa.Uuid(), nullable=False),
        sa.Column("prod_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prd_capacity", sa.Integer(), nullable=False),
        sa.Column("prd_price", sa.Float(), nullable=False),
        sa.Column("prd_gst", sa.Float(), nullable=False),
        sa.Column("ctg_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ctg_id"],
            ["category.ctg_id"],
        ),
        sa.PrimaryKeyConstraint("prd_id"),
    )
    op.create_table(
        "requirementproducts",
        sa.Column("prd_req_id", sa.Uuid(), nullable=False),
        sa.Column("req_id", sa.Uuid(), nullable=False),
        sa.Column("prod_id", sa.Uuid(), nullable=False),
        sa.Column("prod_quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prod_id"],
            ["product.prd_id"],
        ),
        sa.ForeignKeyConstraint(
            ["req_id"],
            ["requirement.req_id"],
        ),
        sa.PrimaryKeyConstraint("prd_req_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("requirementproducts")
    op.drop_table("product")
    op.drop_table("requirement")
    op.drop_table("category")
    # ### end Alembic commands ###
