"""version 2 changes

Revision ID: 442ea77b9a41
Revises: d3190230140f
Create Date: 2025-09-09 23:23:19.404192

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "442ea77b9a41"
down_revision: Union[str, Sequence[str], None] = "d3190230140f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column(
            "client_billing_to_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "client_billing_to_2", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "client_billing_to_3", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "client_billing_from_1", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "client_billing_from_2", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "client_billing_from_3", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "client_ba_holder_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "client_ba_acc_no",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
        sa.Column(
            "client_ba_ifsc_no",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
        sa.Column(
            "client_ba_branch", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("client_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("client_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.drop_table("quotation")
    op.add_column(
        "product",
        sa.Column(
            "show_prd_product",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "product",
        sa.Column(
            "show_prd_price",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "product",
        sa.Column(
            "show_prd_quantity",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "show_prd_quantity")
    op.drop_column("product", "show_prd_price")
    op.drop_column("product", "show_prd_product")
    op.create_table(
        "quotation",
        sa.Column("quot_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quot_expire_date", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quot_billing_to_1", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quot_billing_to_2", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quot_billing_to_3", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quot_billing_from_1", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quot_billing_from_2", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quot_billing_from_3", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quot_ba_holder_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("quot_ba_acc_no", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("quot_ba_ifsc_no", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("quot_ba_branch", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "quot_warranty_panel", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quot_warranty_Inverter", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quot_warranty_battery", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("req_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["req_id"],
            ["requirement.req_id"],
            name=op.f("quotation_req_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("quot_id", name=op.f("quotation_pkey")),
    )
    op.drop_table("clients")
    # ### end Alembic commands ###
