"""Added unique constraint for the ConsumerReqProd table with con_req and prod id

Revision ID: c2ef8e44855c
Revises: cc1f8e4e4584
Create Date: 2025-09-16 20:47:01.711600

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ef8e44855c'
down_revision: Union[str, Sequence[str], None] = 'cc1f8e4e4584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_con_req_prd', 'consumer_requirement_products', ['con_req_id', 'prd_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_con_req_prd', 'consumer_requirement_products', type_='unique')
    # ### end Alembic commands ###
