"""Added created_on and updated_on on every table 

Revision ID: 1298ceb8f0e0
Revises: c2ef8e44855c
Create Date: 2025-09-17 20:43:50.982246

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1298ceb8f0e0'
down_revision: Union[str, Sequence[str], None] = 'c2ef8e44855c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appliances', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('appliances', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('category', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('category', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('clientconsumer', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('clientconsumer', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('clients', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('consumer_requirement', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('consumer_requirement_products', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('consumer_requirement_products', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('consumerappliancesusage', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('consumerappliancesusage', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('product', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('product', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('requirement', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('requirement', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('requirement', 'created_at')
    op.add_column('requirementproducts', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('requirementproducts', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirementproducts', 'updated_on')
    op.drop_column('requirementproducts', 'created_on')
    op.add_column('requirement', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('requirement', 'updated_on')
    op.drop_column('requirement', 'created_on')
    op.drop_column('product', 'updated_on')
    op.drop_column('product', 'created_on')
    op.drop_column('consumerappliancesusage', 'updated_on')
    op.drop_column('consumerappliancesusage', 'created_on')
    op.drop_column('consumer_requirement_products', 'updated_on')
    op.drop_column('consumer_requirement_products', 'created_on')
    op.drop_column('consumer_requirement', 'updated_on')
    op.drop_column('clients', 'updated_on')
    op.drop_column('clientconsumer', 'updated_on')
    op.drop_column('clientconsumer', 'created_on')
    op.drop_column('category', 'updated_on')
    op.drop_column('category', 'created_on')
    op.drop_column('appliances', 'updated_on')
    op.drop_column('appliances', 'created_on')
    # ### end Alembic commands ###
