"""consumer appliance usage table added

Revision ID: 4747694fdc57
Revises: dc3c2b3d6c8b
Create Date: 2025-09-13 01:45:49.365732

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4747694fdc57"
down_revision: Union[str, Sequence[str], None] = "dc3c2b3d6c8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consumerappliancesusage",
        sa.Column("appliance_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("appliance_watt", sa.Float(), nullable=False),
        sa.Column("appliance_quantity", sa.Integer(), nullable=False),
        sa.Column("appliance_day_usage", sa.Float(), nullable=False),
        sa.Column("appliance_night_usage", sa.Float(), nullable=False),
        sa.Column("exclude_for_calculation", sa.Boolean(), nullable=False),
        sa.Column("ccm_id", sa.Uuid(), nullable=False),
        sa.Column("cau_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ccm_id"], ["clientconsumer.ccm_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("cau_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("consumerappliancesusage")
    # ### end Alembic commands ###
