"""modified client Requirement description field

Revision ID: 1441a9c453f1
Revises: 8b415d9821fc
Create Date: 2025-09-10 00:52:14.732510

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1441a9c453f1"
down_revision: Union[str, Sequence[str], None] = "8b415d9821fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_requirement_products",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_requirement_products", "description")
    # ### end Alembic commands ###
